# syntax=docker/dockerfile:1

FROM node:22-alpine as build
WORKDIR /app

# Instalacja zależności
COPY package*.json ./
RUN npm ci

# Kopiujemy kod
COPY . .

# Budujemy aplikację
RUN npm run build

# -------------------------------------
FROM nginx:alpine

# Kopiowanie zbudowanego frontendu
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
