# syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /app

# 1. Kopiujemy package.json i package-lock.json
COPY package*.json ./

# 2. Instalujemy tylko zależności produkcyjne
RUN npm ci --only=production

# 3. Kopiujemy resztę plików
COPY . .

# 4. Otwieramy port
EXPOSE 5000

# 5. Uruchamiamy backend
CMD ["node", "index.js"]
